export const todosTypes = {
    FETCH_TODOS_PENDING: 'FETCH_TODOS_PENDING',
    FETCH_TODOS_FULFILLED: 'FETCH_TODOS_FULFILLED',
    FETCH_TODOS_REJECTED: 'FETCH_TODOS_REJECTED',
    NEW_TODO: 'NEW_TODO',
    SAVE_TODO: 'SAVE_TODO',
    FETCH_TODOS_BY_ID_PENDING: 'FETCH_TODOS_BY_ID_PENDING',
    FETCH_TODOS_BY_ID_FULFILLED: 'FETCH_TODOS_BY_ID_FULFILLED',
    FETCH_TODOS_BY_ID_REJECTED: 'FETCH_TODOS_BY_ID_REJECTED',
    UPDATE_TODO: 'UPDATE_TODO',
    DELETE_TODO: 'DELETE_TODO'
};